#include "ultrasonic.h"

ICU_ConfigType icuconfig = {
    .clock = F_CPU_8,
    .edge = RAISING};

void Ultrasonic_init(void)
{
    // Initialize the ICU driver as required
    ICU_init(&icuconfig);
    // Setup the ICU call back function.
    ICU_setCallBack(&Ultrasonic_edgeProcessing);
    // Setup the direction for the trigger pin as output pin through the GPIO driver.
    GPIO_setPinDirection(PORTB_ID,PIN5_ID,PIN_INPUT);
}
void Ultrasonic_Trigger(void)
{
    // Send the Trigger pulse to the ultrasonic.
}
/**
 * @brief
 * ➢ Send the trigger pulse by using Ultrasonic_Trigger function.
 * ➢ Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void)
{
    Ultrasonic_Trigger();
    
}
/**
 * @brief
 * ➢ This is the call back function called by the ICU driver.
 * ➢ This is used to calculate the high time (pulse time) generated by
 *   the ultrasonic sensor.
 *
 */
void Ultrasonic_edgeProcessing(void)
{
}
